<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AspNetCore.HealthChecks.UI" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    <PackageVersion Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="9.0.0" />
    <PackageVersion Include="Duende.IdentityModel" Version="8.1.0" />
    <PackageVersion Include="KubernetesClient" Version="19.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.5" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Scriban" Version="6.6.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageVersion Include="Volo.Abp.Account.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Account.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Account.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Account.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Account.Web.OpenIddict" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Authentication.JwtBearer" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Serilog" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AuditLogging.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AuditLogging.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.AuditLogging.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Autofac" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BackgroundJobs.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BackgroundJobs.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BackgroundJobs.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BlobStoring.Database.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BlobStoring.Database.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.BlobStoring.Database.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Caching" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Emailing" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.FeatureManagement.Web" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.GlobalFeatures" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Identity.Web" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.OpenIddict.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.OpenIddict.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.OpenIddict.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.Domain.Identity" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.Domain.OpenIddict" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.PermissionManagement.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.SettingManagement.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.Studio.Client.AspNetCore" Version="2.2.1" />
    <PackageVersion Include="Volo.Abp.Swashbuckle" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.Application" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.Application.Contracts" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.Domain" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.Domain.Shared" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.EntityFrameworkCore" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.HttpApi" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.HttpApi.Client" Version="10.1.1" />
    <PackageVersion Include="Volo.Abp.TenantManagement.Web" Version="10.1.1" />
  </ItemGroup>
</Project>