<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>EasterOctathlon</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasterOctathlon.Domain.Shared\EasterOctathlon.Domain.Shared.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application.Contracts" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application.Contracts" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Identity.Application.Contracts" />
    <PackageReference Include="Volo.Abp.Account.Application.Contracts" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application.Contracts" />
  </ItemGroup>

</Project>
